# ==========================================
# CINEBOOK - DATABASE CONFIGURATION
# ==========================================

# 1. MySQL Database Connection URL
# Yahan 'cinebook_db' hamare database ka naam hai
spring.datasource.url=jdbc:mysql://localhost:3306/cinebook_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# 2. MySQL Username and Password 
# (Agar aapka MySQL password kuch aur hai, toh 'root' ki jagah wo likh dena)
spring.datasource.username=root
spring.datasource.password=root123

# 3. MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# HIBERNATE / JPA CONFIGURATION
# ==========================================

# 'update' ka matlab hai ki Spring Boot khud check karega aur agar table nahi hai toh bana dega
spring.jpa.hibernate.ddl-auto=update

# Console mein SQL queries dekhne ke liye (Debugging mein bahut kaam aayega)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Server Port (Default 8080 hota hai, hum isko 8080 hi rakhenge)
server.port=8080